import { chromium, type FullConfig } from '@playwright/test';

/**
 * Global setup: runs once before all test projects.
 * Currently a no-op — auth state is generated by the 'setup' project.
 */
async function globalSetup(_config: FullConfig) {
  // No-op — auth setup is handled by tests/auth.setup.ts
  return;
}

export default globalSetup;
